# Generated by Django 3.1.2 on 2024-05-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solicitudpago_compra_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpago',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
