# Generated by Django 3.1.2 on 2024-05-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_solicitudpago_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpago',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
